### ISSUE TITLE
Add support for Desktop Deduplication Win10

### ISSUE THREAD

**Issue by itapi** [smasherprog/Remote_Access_Library#31]
The desktop duplication api service provides fast screenshot and information about changed area.
https://msdn.microsoft.com/en-us/library/windows/desktop/hh404487(v=vs.85).aspx
https://code.msdn.microsoft.com/windowsdesktop/Desktop-Duplication-Sample-da4c696a

check this out :)

**Comment by smasherprog** [comment]
I did look into this, but I havent got around to implementing it. This method is about 5 times faster for screen retrievals. In my tests, it was about 50 ms to pull 2 1920x1080 screens with the standard method, and it was about 8 ms to do it using the above method.

It is something that I will look into adding but it wont be until I am done with everything else. The reason is that its a fair amount of code to get it going and my current implementation is slow, but it works on all windows platforms and its fast enough that its not noticeable.

Having said that, if you want to jump in and get started with that, please do :)

**Comment by itapi** [comment]
@smasherprog  unfortunately my knowledge in c++ isn't enough for doing this, im actually expert at c# only :(

**Comment by smasherprog** [comment]
This is in-progress right now and almost done on my other repo https://github.com/smasherprog/Screen_Capture
I am putting all of my screen/mouse capturing in that repo so it can be separate from this repo.

**Comment by itapi** [comment]
@smasherprog  nice! would you keep maintaining the screen sharing project?
because i'm also working on small project...using libjpeg-turbo..and the desktop api.. 
:)
glad to hear from you :)

**Comment by smasherprog** [comment]
Yeah, I am working on creating a cross-plat screen/mouse capturing library, then I am coming back to this project to incorporate that module.
I want to make things as reusable as possible for me and others so I am going to break as much up into separate repos as possible. The reason I revisited this is because I have three (3)  4K monitors and the GDI method is really slow.

**Comment by smasherprog** [comment]
Implementation added to codebase.

**Comment by smasherprog** [comment]
Its in the Screen Capture Library that will be a part of this repo 
https://github.com/smasherprog/Screen_Capture
